name: Commit checker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out Code
        uses: actions/checkout@v4

      # Setup JDK 23
      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Build the project
      - name: Build
        run: ./gradlew clean build

      # Run tests
      - name: Test
        run: ./gradlew test