name: Commit checker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Code check out
      - name: Check out Code
        uses: actions/checkout@v4

      # Use java 23
      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Set X11
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      # Install needed dependencies
      - name: Install dependencies
        run: sudo apt-get install libgl1-mesa-dev xorg-dev

      # Install GLFW dependencies
      - name: Install GLFW dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev

      # Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Build + Sonar check
      - name: Build and Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info