name: Commit checker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Code check out
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use java 23
      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Check Ubuntu Version
        run: lsb_release -a

      # Set X11
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Update package list
        run: sudo apt-get update

      - name: Enable Universe and Multiverse Repositories
        run: |
          sudo add-apt-repository universe
          sudo add-apt-repository multiverse
          sudo apt-get update

      # Install needed dependencies
      - name: Install dependencies
        run: sudo apt-get install libgl1-mesa-dev xorg-dev

      # Install GLFW dependencies
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 &

      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      # Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport

      # Build and Sonar qube
      - name: Build and Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info